
export const SET_USER = 'SET_USER';

export const FETCH_PINS_FROM_API_LOADING = 'FETCH_PINS_FROM_API_LOADING';
export const FETCH_PINS_FROM_API_SUCCESS = 'FETCH_PINS_FROM_API_SUCCESS';
export const FETCH_PINS_FROM_API_ERROR = 'FETCH_PINS_FROM_API_ERROR';

export const FETCH_PIN_URL_FROM_API_LOADING = 'FETCH_PINS_FROM_API_LOADING';
export const FETCH_PIN_URL_FROM_API_SUCCESS = 'FETCH_PINS_FROM_API_SUCCESS';
export const FETCH_PIN_URL_FROM_API_ERROR = 'FETCH_PINS_FROM_API_ERROR';

export const ADD_PIN = 'ADD_PIN';
export const DELETE_PIN = 'RESET_PIN';
